import Link from "next/link";
import { Footer, Nav } from "./components";
import { products } from "../lib/catalog";
import { marketplaceMetrics } from "../lib/reviews";

export const revalidate = 60;

export default async function Home() {
  const metrics = await marketplaceMetrics();
  const membership = products[0];
  return <main className="shell"><Nav /><section className="hero"><div className="eyebrow">PRIVACY-PRESERVING REVIEWS</div><h1>Real customers.<br />Verified experiences.<br /><span className="accent">Private by design.</span></h1><p>VerifyTrust confirms that a review comes from a genuine purchase without exposing the person, payment or private data behind it.</p><div className="actions"><Link className="button" href="/marketplace">EXPLORE VERIFIED REVIEWS</Link><Link className="button secondary" href="/for-businesses">ADD YOUR BUSINESS</Link></div><p className="trust-line" style={{ marginTop: 22 }}>Purchase verified · Identity protected · Duplicate reviews prevented</p></section><section className="section"><div className="label">FIRST LIVE INTEGRATION</div><div className="featured-card"><div><h2>Longhand</h2><p className="large-copy">A real postcard, and the private story behind it.</p><p>Longhand is the first merchant using VerifyTrust to connect a real Stripe purchase with a privacy-preserving product review.</p><div className="badges compact"><span>Live pilot</span><span>Real payment</span><span>Verified reviews</span><span>Privacy protected</span></div></div><div className="actions"><Link className="button" href="/merchant/longhand">VIEW LONGHAND REVIEWS</Link><a className="button secondary" href="https://longhand.cards" target="_blank" rel="noreferrer">VISIT LONGHAND.CARDS ↗</a></div></div></section><section className="section"><div className="featured-product"><div><div className="eyebrow">LONGHAND · LIVE VERIFICATION PRODUCT</div><h2>{membership.name}</h2><p>Join the first live VerifyTrust merchant experience. Complete a real $1 payment and leave one verified review without making your identity or payment details public.</p></div><div><strong className="price">Price: {membership.priceLabel}</strong><Link className="button" href="/merchant/longhand/verified-membership">JOIN AND REVIEW FOR $1</Link></div></div></section><section className="section"><div className="metrics">{[[metrics.merchants === 1 ? "live pilot" : "live pilots", metrics.merchants], ["listed products", metrics.products], ["verified reviews", metrics.verifiedReviews], ["duplicate attempts prevented", metrics.preventedDuplicates]].map(([label, value]) => <div className="metric" key={label}><strong>{value ?? "—"}</strong><span>{label}</span></div>)}</div><p className="muted-small">Verified review count source: {metrics.metricsSource}</p></section><section className="section"><div className="label">HOW IT WORKS</div><div className="how-strip">{["Buy", "Receive a private credential", "Prove eligibility on your device", "Publish a verified review"].map((step, index) => <div key={step}><span>0{index + 1}</span><strong>{step}</strong></div>)}</div><p className="coming-soon">More integrations coming soon</p></section><Footer /></main>;
}
