[package]
name = "proof_of_review"
type = "bin"
authors = ["Verify Trust"]
compiler_version = ">=1.0.0"

[dependencies]
schnorr = { git = "https://github.com/noir-lang/schnorr", tag = "v0.4.0" }
poseidon = { git = "https://github.com/noir-lang/poseidon", tag = "v0.3.0" }
